services:
  postgres:
    image: postgres:18rc1-alpine
    container_name: fastapi-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastapi
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    container_name: fastapi-redis
    command: redis-server --port 6379
    restart: always
    ports:
      - "6379:6379"

#  app:
#    build:
#      context: ..
#      dockerfile: docker/Dockerfile
#    container_name: fastapi-web
#    command: uvicorn main:app --host 0.0.0.0 --reload
#    volumes:
#      - .:/app
#    ports:
#      - "8000:8000"
#    depends_on:
#      - postgres
#      - redis

volumes:
  postgres_data:
